//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kolcsonze
    {
        public int Id { get; set; }
        public int Konyv_ID { get; set; }
        public int Szemely_ID { get; set; }
        public System.DateTime Kivetel_datum { get; set; }
        public Nullable<System.DateTime> Visszahozas_datum { get; set; }
    
        public virtual Konyv Konyv { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
