//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tag(DateTime Szuletesi_datum) // ide felsorolni id,nev...
        {
            _Szuletsi_datum = Szuletesi_datum;
            this.Kolcsonzes = new HashSet<Kolcsonze>();
        }
    
        public int tag_Id { get; }
        public string Nev { get; set; }
        public System.DateTime Szuletesi_datum { get; set; }
        private System.DateTime _Szuletsi_datum;
        public string Cim { get; set; }
        public System.DateTime Belepesi_datum { get; set; }
        public Nullable<System.DateTime> Kilepesi_datum { get; set; } // set-ben kisebb legyen mint belepesi datum vagy hiba
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kolcsonze> Kolcsonzes { get; set; }
    }
}
